version: 2.1
jobs:
  test:
    docker:
      - image: cimg/base:stable

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            make setup-ubuntu
            unset PYENV_ROOT
            git clone https://github.com/pyenv/pyenv.git ~/.pyenv
            echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
            echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
            echo 'eval "$(pyenv init -)"' >> ~/.bashrc
      
      - run:
          name: Install Python
          command: |
            source /home/circleci/.bashrc
            pyenv root
            pyenv install 3.6.15
            pyenv install 3.10.3
            pyenv local 3.6.15 3.10.3
            pyenv versions
            python -m venv venv
            venv/bin/pip install -r requirements_test.txt

      - run:
          name: Run Tests
          command: |
            venv/bin/tox

workflows:
  version: 2.1
  common-build:
    # will run for every command AND for every tag that fits the regex
    jobs:
      - test:
          filters:
            tags:
              only: /v\d+.\d+.\d+/