version: 2.1
jobs:
  test:
    docker:
      - image: cimg/base:stable

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            make setup-ubuntu
            unset PYENV_ROOT
            curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
            export PATH="$HOME/.pyenv/shims:$HOME/.pyenv/bin:$PATH"
            pyenv install 3.6.15 3.10.4
            pyenv global 3.6.15 3.10.4
            python -m venv venv
            venv/bin/pip install -r requirements_test.txt

      - run:
          name: Run Tests
          command: |
            venv/bin/tox

workflows:
  version: 2.1
  common-build:
    # will run for every command AND for every tag that fits the regex
    jobs:
      - test:
          filters:
            tags:
              only: /v\d+.\d+.\d+/