version: 2.1
jobs:
  test:
    docker:
      - image: cimg/python:3.10.4

    steps:
      - checkout

      - restore_cache:
          key: pyenv-v1-{{ checksum "/home/circleci/.pyenv/version" }}

      - run:
          name: Install Python Versions and Dependencies
          command: |
            # make setup-ubuntu
            # git clone https://github.com/pyenv/pyenv.git ~/.pyenv
            # echo 'export PYENV_ROOT="$HOME/.pyenv"' >> $BASH_ENV
            # echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> $BASH_ENV
            # echo 'eval "$(pyenv init -)"' >> $BASH_ENV
            # echo ${PYENV_ROOT}
            # source $BASH_ENV
            pyenv install 3.6.15
            pyenv install 3.7.13
            pyenv install 3.8.13
            pyenv install 3.9.12
            pyenv local 3.6.15 3.7.13 3.8.13 3.9.12 3.10.4
            pyenv versions
            python -m venv venv
            venv/bin/pip install -r requirements_test.txt
      
      - save_cache:
          paths:
            - ./venv
            - /home/circleci/.pyenv/
          key: pyenv-v1-{{ checksum "/home/circleci/.pyenv/version" }}

      - run:
          name: Run Tests
          command: |
            venv/bin/tox

workflows:
  version: 2.1
  common-build:
    jobs:
      - test:
          filters:
            tags:
              only: /v\d+.\d+.\d+/